// QEMUBundleSupport: utility functions backing the setup checklist.
//
// The checklist surfaces three pieces of state:
//   - whether the .app is in /Applications (required for the dext to load)
//   - whether the system extension is activated
//   - whether CLI shims are installed in ~/.local/bin
//
// The CLI shim is a tiny shell wrapper rather than a bare symlink so we can
// inject `-L <bundled-firmware>` automatically; otherwise users would have to
// remember to pass it on every invocation.

import AppKit
import Foundation

/// CLI tools we install wrappers for under `~/.local/bin`. Order is the order
/// the install/uninstall actions iterate in (and the order shown in errors).
///
/// `qemu-vfio-apple` is always present in the bundle (built by embed-qemu.sh).
/// When a `dist/` directory is available at build time, both
/// `qemu-system-aarch64` and `qemu-img` are embedded and wrapped.
/// `installCli` skips tools that aren't present in the bundle so a UI-only
/// build still installs just the qemu-vfio-apple wrapper.
let kCliTools = ["qemu-system-aarch64", "qemu-img", "qemu-vfio-apple"]

// MARK: - Bundle layout

struct BundleLayout {
    let bundleURL: URL

    var contentsURL:    URL { bundleURL.appendingPathComponent("Contents") }
    var macOSURL:       URL { contentsURL.appendingPathComponent("MacOS") }
    var frameworksURL:  URL { contentsURL.appendingPathComponent("Frameworks") }
    var resourcesURL:   URL { contentsURL.appendingPathComponent("Resources") }
    var shareURL:       URL { resourcesURL.appendingPathComponent("share/qemu") }
    var qemuBinaryURL:  URL { macOSURL.appendingPathComponent("qemu-system-aarch64") }
    var cliBinaryURL:   URL { macOSURL.appendingPathComponent("qemu-vfio-apple") }
    var hostBinaryURL:  URL { Bundle.main.executableURL ?? macOSURL.appendingPathComponent("VFIOUserHostApp") }

    static var current: BundleLayout {
        return BundleLayout(bundleURL: Bundle.main.bundleURL)
    }

    var isQemuBundled: Bool {
        FileManager.default.fileExists(atPath: qemuBinaryURL.path)
    }

    var isCliBundled: Bool {
        FileManager.default.fileExists(atPath: cliBinaryURL.path)
    }

    /// Path inside the bundle for the given CLI tool name.
    func bundlePath(forTool tool: String) -> URL {
        macOSURL.appendingPathComponent(tool)
    }

    /// True iff the given CLI tool was actually compiled/copied into this
    /// bundle. UI-only builds skip the dist-provided QEMU tools.
    func isToolBundled(_ tool: String) -> Bool {
        FileManager.default.fileExists(atPath: bundlePath(forTool: tool).path)
    }
}

// MARK: - Location state

enum LocationState: Equatable {
    case ok
    case wrongPlace(currentPath: String)
}

func locationState(_ layout: BundleLayout) -> LocationState {
    let p = layout.bundleURL.path
    if p.hasPrefix("/Applications/") { return .ok }
    return .wrongPlace(currentPath: p)
}

// MARK: - CLI install state

enum CliState: Equatable {
    /// Wrapper present and points at this bundle.
    case ok(path: String)
    /// File exists but points at a different bundle, or is a bare symlink, or
    /// otherwise doesn't match what we'd write today. Reinstall to fix.
    case stale(path: String, reason: String)
    case missing
}

func cliInstallDir() -> URL {
    FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".local/bin")
}

/// Returns the wrapper script body we want to install for `tool` given the
/// current bundle layout. The wrapper is a thin `exec` shim into the bundled
/// binary; for `qemu-system-aarch64` we also inject `-L <bundled-firmware>`
/// so users never have to pass it manually. Other tools like `qemu-img` use a
/// plain passthrough wrapper.
func cliWrapperContent(_ layout: BundleLayout, tool: String) -> String {
    let bundlePath = layout.bundlePath(forTool: tool).path
    let header = """
        #!/bin/sh
        # Auto-generated by VFIOUserHostApp. Do not edit; reinstall via the app.
        # Bundle: \(layout.bundleURL.path)
        """

    switch tool {
    case "qemu-system-aarch64":
        let share = layout.shareURL.path
        return """
            \(header)
            exec "\(bundlePath)" -L "\(share)" "$@"

            """
    default:
        // qemu-vfio-apple and any future tool: plain exec passthrough.
        return """
            \(header)
            exec "\(bundlePath)" "$@"

            """
    }
}

func cliState(_ layout: BundleLayout, tool: String) -> CliState {
    let link = cliInstallDir().appendingPathComponent(tool)
    let fm = FileManager.default
    guard fm.fileExists(atPath: link.path) else { return .missing }

    // A bare symlink (from an older install) still works for launching but
    // bypasses our `-L` injection. Treat it as stale so the user reinstalls.
    if let attrs = try? fm.attributesOfItem(atPath: link.path),
       attrs[.type] as? FileAttributeType == .typeSymbolicLink
    {
        return .stale(path: link.path, reason: "old symlink (no firmware path)")
    }

    guard let data = try? Data(contentsOf: link),
          let body = String(data: data, encoding: .utf8)
    else {
        return .stale(path: link.path, reason: "unreadable")
    }

    let expected = cliWrapperContent(layout, tool: tool)
    return body == expected
        ? .ok(path: link.path)
        : .stale(path: link.path, reason: "points at a different bundle")
}

/// True iff `~/.local/bin` (or wherever `cliInstallDir()` resolves to) is on
/// the user's effective PATH.
///
/// GUI apps launched from Finder/Dock inherit launchd's PATH
/// (`/usr/bin:/bin:/usr/sbin:/sbin`) rather than the user's interactive shell
/// PATH, so checking `ProcessInfo.environment["PATH"]` alone reports "not in
/// PATH" even when the user has it in their `.zshrc`. We additionally spawn
/// the user's login shell once and read `$PATH` from it.
///
/// Result is memoised — the shell spawn is bounded to ~2s but we don't want
/// to repeat it on every SwiftUI render.
func pathContainsCliDir() -> Bool {
    PathCheck.shared.contains(cliInstallDir().path)
}

private final class PathCheck {
    static let shared = PathCheck()

    private let lock = NSLock()
    private var cache: [String: Bool] = [:]

    func contains(_ dir: String) -> Bool {
        lock.lock()
        if let cached = cache[dir] {
            lock.unlock()
            return cached
        }
        lock.unlock()

        let result = computeContains(dir)

        lock.lock()
        cache[dir] = result
        lock.unlock()
        return result
    }

    func invalidate() {
        lock.lock()
        cache.removeAll()
        lock.unlock()
    }

    private func computeContains(_ dir: String) -> Bool {
        if let inherited = ProcessInfo.processInfo.environment["PATH"],
           splitPath(inherited).contains(dir)
        {
            return true
        }
        if let user = userShellPath(), splitPath(user).contains(dir) {
            return true
        }
        return false
    }

    private func splitPath(_ s: String) -> [String] {
        s.split(separator: ":").map(String.init)
    }

    /// Asks the user's login + interactive shell what `$PATH` it produces.
    /// Bounded to ~2s so a misbehaving rc file can't stall the UI.
    private func userShellPath() -> String? {
        let shell = ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
        guard FileManager.default.isExecutableFile(atPath: shell) else { return nil }

        let task = Process()
        task.executableURL = URL(fileURLWithPath: shell)
        // -l: source profile/login files (.zprofile / .profile)
        // -i: source interactive rc files (.zshrc / .bashrc) — most users
        //     set PATH there
        task.arguments = ["-l", "-i", "-c", "printf %s \"$PATH\""]
        let stdout = Pipe()
        let stderr = Pipe()
        task.standardOutput = stdout
        task.standardError = stderr
        task.standardInput = FileHandle(forReadingAtPath: "/dev/null")

        do {
            try task.run()
        } catch {
            return nil
        }

        let deadline = Date().addingTimeInterval(2.0)
        while task.isRunning && Date() < deadline {
            Thread.sleep(forTimeInterval: 0.05)
        }
        if task.isRunning {
            task.terminate()
            return nil
        }

        let data = stdout.fileHandleForReading.readDataToEndOfFile()
        let s = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return (s?.isEmpty ?? true) ? nil : s
    }
}

/// Aggregates per-tool `cliState` into a single state for the UI:
///
///   - `.ok`      iff every bundled tool has a matching wrapper installed
///   - `.stale`   if any tool's wrapper exists but doesn't match
///   - `.missing` if any tool is bundled but has no wrapper installed
///
/// Tools that aren't present in the bundle are ignored (so a UI-only build
/// doesn't show "missing qemu-system-aarch64" forever).
func cliAggregateState(_ layout: BundleLayout) -> CliState {
    var staleHit: (path: String, reason: String)? = nil
    var anyMissing = false
    var anyChecked = false

    for tool in kCliTools where layout.isToolBundled(tool) {
        anyChecked = true
        switch cliState(layout, tool: tool) {
        case .ok:
            continue
        case .missing:
            anyMissing = true
        case .stale(let path, let reason):
            if staleHit == nil {
                staleHit = (path: path, reason: "\(tool): \(reason)")
            }
        }
    }

    if !anyChecked {
        // Nothing to install (UI-only build with no bundled tools at all).
        return .ok(path: cliInstallDir().path)
    }
    if anyMissing { return .missing }
    if let s = staleHit { return .stale(path: s.path, reason: s.reason) }
    return .ok(path: cliInstallDir().path)
}

@discardableResult
func installCli(_ layout: BundleLayout) -> [String] {
    let dir = cliInstallDir()
    let fm = FileManager.default
    var actions: [String] = []
    do {
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
    } catch {
        return ["FAILED to create \(dir.path): \(error.localizedDescription)"]
    }
    for tool in kCliTools {
        // Skip tools that weren't compiled/copied into this bundle so a
        // UI-only build doesn't try to install a wrapper that points at a
        // nonexistent binary.
        guard layout.isToolBundled(tool) else { continue }

        let dest = dir.appendingPathComponent(tool)
        try? fm.removeItem(at: dest)
        let body = cliWrapperContent(layout, tool: tool)
        do {
            try body.write(to: dest, atomically: true, encoding: .utf8)
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: dest.path)
            actions.append("installed \(dest.path)")
        } catch {
            actions.append("FAILED to write \(dest.path): \(error.localizedDescription)")
        }
    }
    return actions
}

@discardableResult
func uninstallCli() -> [String] {
    var actions: [String] = []
    let dir = cliInstallDir()
    for tool in kCliTools {
        let link = dir.appendingPathComponent(tool)
        if FileManager.default.fileExists(atPath: link.path) {
            try? FileManager.default.removeItem(at: link)
            actions.append("removed \(link.path)")
        }
    }
    // Also clean up the rc-file PATH entry we may have added.
    switch removeCliDirFromPath() {
    case .removed(let file):
        actions.append("removed PATH entry from \(file)")
    case .notConfigured, .unsupportedShell:
        break
    case .failed(let err):
        actions.append("FAILED to clean up PATH entry: \(err)")
    }
    return actions
}

// MARK: - Adding the install dir to the user's shell PATH

enum AddToPathResult {
    /// Already on PATH (no change made).
    case alreadyOnPath
    /// Our marker is already present in the rc file but the entry isn't yet
    /// visible to subshells — usually means the user hasn't opened a new shell
    /// since installing.
    case alreadyConfigured(file: String)
    /// We appended the snippet to `file`. User must open a new shell tab for
    /// it to take effect.
    case appended(file: String)
    /// Shell isn't sh-compatible (e.g. fish, nushell) — show manual instructions.
    case unsupportedShell(name: String, file: String?)
    case failed(error: String)
}

private let kPathSnippetMarker     = "# >>> VFIOUserHostApp PATH (auto-managed) >>>"
private let kPathSnippetEndMarker  = "# <<< VFIOUserHostApp PATH (auto-managed) <<<"

/// Appends `cliInstallDir()` to the user's shell `PATH` by editing the right
/// rc file for their login shell. Idempotent — if our marker is already in the
/// file, we don't write anything.
func addCliDirToPath() -> AddToPathResult {
    if pathContainsCliDir() { return .alreadyOnPath }

    let shell = ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
    let shellName = (shell as NSString).lastPathComponent
    let home = FileManager.default.homeDirectoryForCurrentUser
    let dirLiteral = "$HOME/.local/bin"   // matches cliInstallDir()

    let rcURL: URL
    let snippet: String
    switch shellName {
    case "zsh":
        // .zshrc is sourced for both login and interactive shells, which is
        // what we want — PATH from .zprofile would be missed by some
        // terminal emulators that start non-login shells.
        rcURL = home.appendingPathComponent(".zshrc")
        snippet = """
            \(kPathSnippetMarker)
            export PATH="\(dirLiteral):$PATH"
            \(kPathSnippetEndMarker)
            """
    case "bash":
        // On macOS bash uses .bash_profile for login shells.
        rcURL = home.appendingPathComponent(".bash_profile")
        snippet = """
            \(kPathSnippetMarker)
            export PATH="\(dirLiteral):$PATH"
            \(kPathSnippetEndMarker)
            """
    case "sh", "dash", "ksh":
        rcURL = home.appendingPathComponent(".profile")
        snippet = """
            \(kPathSnippetMarker)
            export PATH="\(dirLiteral):$PATH"
            \(kPathSnippetEndMarker)
            """
    default:
        // fish, nushell, etc. — different syntax; let the user handle it.
        return .unsupportedShell(name: shellName, file: nil)
    }

    let fm = FileManager.default
    let existing: String
    if fm.fileExists(atPath: rcURL.path) {
        existing = (try? String(contentsOf: rcURL, encoding: .utf8)) ?? ""
    } else {
        existing = ""
    }

    if existing.contains(kPathSnippetMarker) {
        // Marker already present but pathContainsCliDir() returned false —
        // user probably hasn't opened a new shell since the last install.
        PathCheck.shared.invalidate()
        return .alreadyConfigured(file: rcURL.path)
    }

    let separator = (existing.isEmpty || existing.hasSuffix("\n")) ? "" : "\n"
    let newContent = existing + separator + "\n" + snippet + "\n"

    do {
        try newContent.write(to: rcURL, atomically: true, encoding: .utf8)
    } catch {
        return .failed(error: error.localizedDescription)
    }

    // Force the next pathContainsCliDir() to re-spawn the shell so the UI
    // reflects the new state. (The shell will source the just-modified rc.)
    PathCheck.shared.invalidate()
    return .appended(file: rcURL.path)
}

// MARK: - Removing the rc-file PATH entry

enum RemoveFromPathResult {
    /// No managed marker found in the user's rc file (nothing to do).
    case notConfigured
    /// We removed our marker block from `file`.
    case removed(file: String)
    /// We don't manage rc files for this shell (fish, nushell, etc.).
    case unsupportedShell(name: String)
    case failed(error: String)
}

/// Inverse of `addCliDirToPath()`: locates the rc file for the user's shell
/// and removes the auto-managed marker block we previously inserted. Safe to
/// call when nothing was ever added (returns `.notConfigured`).
func removeCliDirFromPath() -> RemoveFromPathResult {
    let shell = ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
    let shellName = (shell as NSString).lastPathComponent
    let home = FileManager.default.homeDirectoryForCurrentUser

    let rcURL: URL
    switch shellName {
    case "zsh":               rcURL = home.appendingPathComponent(".zshrc")
    case "bash":              rcURL = home.appendingPathComponent(".bash_profile")
    case "sh", "dash", "ksh": rcURL = home.appendingPathComponent(".profile")
    default:                  return .unsupportedShell(name: shellName)
    }

    guard FileManager.default.fileExists(atPath: rcURL.path) else {
        return .notConfigured
    }

    do {
        guard try removePathSnippet(from: rcURL) else {
            return .notConfigured
        }
    } catch {
        return .failed(error: error.localizedDescription)
    }

    PathCheck.shared.invalidate()
    return .removed(file: rcURL.path)
}

/// Splices out the marker-delimited block (and one collapsed leading blank
/// line, if present) from `file`. Returns true iff anything was removed.
private func removePathSnippet(from file: URL) throws -> Bool {
    let original = try String(contentsOf: file, encoding: .utf8)
    guard original.contains(kPathSnippetMarker) else { return false }

    var lines = original.components(separatedBy: "\n")
    var start: Int?
    var end: Int?
    for (i, line) in lines.enumerated() {
        if start == nil, line.contains(kPathSnippetMarker) { start = i }
        if start != nil, line.contains(kPathSnippetEndMarker) {
            end = i
            break
        }
    }
    guard let s = start, let e = end, s <= e else {
        // Start marker present but end marker missing — leave the file alone
        // rather than potentially nuke unrelated content.
        return false
    }

    lines.removeSubrange(s...e)
    if s > 0 && lines[s - 1].isEmpty {
        lines.remove(at: s - 1)
    }
    let newContent = lines.joined(separator: "\n")
    try newContent.write(to: file, atomically: true, encoding: .utf8)
    return true
}

// MARK: - Helpers used by the UI

func openSystemSettingsExtensions() {
    if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_SystemExtensions") {
        NSWorkspace.shared.open(url)
    }
}

func revealBundleInFinder(_ layout: BundleLayout) {
    NSWorkspace.shared.activateFileViewerSelecting([layout.bundleURL])
}
