PACKAGE_NAME="apple-dma"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="apple_dma"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make KERNELDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
REMAKE_INITRD="yes"
